apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: infra
stringData:
  POSTGRES_PASSWORD: "changeme"
  POSTGRES_USER: "admin"
  POSTGRES_DB: "crypto_db"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra
spec:
  ports:
    - port: 5432
  selector:
    app: postgres

---
# Using StatefulSet is better for DB, but Deployment + PVC is fine for simple setups.
# Changing to direct volume claim for simplicity in dev.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
